# Generated by Django 6.1.1 on 2026-09-07 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_apertura', models.IntegerField(help_text='Fondo de caja inicial en efectivo')),
                ('monto_cierre_esperado', models.IntegerField(blank=True, null=True)),
                ('monto_cierre_real', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('TUU', 'Terminal TUU (Tarjeta)'), ('EFECTIVO', 'Efectivo')], max_length=20)),
                ('sincronizado_shopify', models.BooleanField(default=False)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='caja.sesioncaja')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.IntegerField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja.ventalocal')),
            ],
        ),
    ]
