# Generated by Django 6.1.1 on 2026-09-07 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventalocal',
            old_name='fecha_hora',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='ventalocal',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ventalocal',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ventalocal',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_TUU', 'Tarjeta TUU'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ventalocal',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='caja.sesioncaja'),
        ),
        migrations.AlterField(
            model_name='ventalocal',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
