# Generated by Django 6.1.1 on 2026-09-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_rename_fecha_hora_ventalocal_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventalocal',
            old_name='fecha',
            new_name='fecha_hora',
        ),
    ]
