# Generated by Django 6.1.1 on 2026-09-15 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_rename_fecha_ventalocal_fecha_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Promo 3 Latas Motta', max_length=100)),
                ('sku_producto', models.CharField(help_text='El SKU exacto al que aplica la promo', max_length=50)),
                ('tipo_promocion', models.CharField(choices=[('VOLUMEN', 'Precio especial por X cantidad (Ej: 3x10000)'), ('N_X_M', 'Llevas N y Pagas M (Ej: 3x2)'), ('POR_MAYOR', 'Precio rebajado desde X unidades')], default='VOLUMEN', max_length=20)),
                ('cantidad_requerida', models.IntegerField(help_text='Cantidad de productos que detonan la promo (Ej: 3)')),
                ('precio_promocional', models.IntegerField(blank=True, help_text='Ej: 10000 (el total por las 3) o 2500 (cada una)', null=True)),
                ('cantidad_pagada', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Dejar en blanco si es indefinida', null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
