# Generated by Django 6.1.1 on 2026-09-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_promocionlocal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocionlocal',
            name='sku_producto',
        ),
        migrations.AddField(
            model_name='promocionlocal',
            name='alcance_tipo',
            field=models.CharField(choices=[('SKU', 'SKU Específico'), ('PROVEEDOR', 'Proveedor (Vendor)'), ('TIPO', 'Tipo de Producto (Categoría)')], default='SKU', max_length=20),
        ),
        migrations.AddField(
            model_name='promocionlocal',
            name='alcance_valor',
            field=models.CharField(default='N/A', help_text='El SKU exacto, el nombre del Proveedor o el Tipo de producto', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocionlocal',
            name='cantidad_requerida',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promocionlocal',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocionlocal',
            name='precio_promocional',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
