# Generated by Django 6.1.1 on 2026-09-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Número de folio del DTE', max_length=50)),
                ('fecha_emision', models.DateField(help_text='Fecha que indica la factura')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, help_text='Cuándo se ingresó al sistema')),
                ('sincronizado_shopify', models.BooleanField(default=False, help_text='True si el inventario ya se actualizó con éxito en Shopify')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT del proveedor (ej: 76.123.456-K)', max_length=12, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código de barras o SKU del producto', max_length=100)),
                ('shopify_variant_id', models.CharField(blank=True, help_text='ID de la variante en Shopify', max_length=50, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo neto de compra', max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.facturacompra')),
            ],
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='compras.proveedor'),
        ),
    ]
